### ISSUE TITLE
Yaml suggestion

### ISSUE THREAD

**Issue by yokeTH** [YaLaewWa/backend#7]
it can be
```yaml

- name: Deploy
    run: |
    ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}
    cd ${{ secrets.WORK_DIR }}
    git pull origin main
    # use docker compose here
```
